//! Systematic Reed–Solomon error-correction codec over GF(256).
//!
//! This follows the classic "Reed–Solomon for coders" construction:
//!
//! - Field GF(256) generated by the primitive polynomial `0x11D`.
//! - Generator element α = 2.
//! - Systematic encoding: the output is the original message bytes followed
//!   by `nsym` parity bytes computed as the remainder of
//!   `message · x^nsym` modulo the generator polynomial.
//! - Decoding (errors only): syndromes → Berlekamp–Massey error locator →
//!   Chien search for error positions → Forney algorithm for magnitudes.
//!
//! Only the Rust standard library is used. GF(256) exp/log tables are
//! computed once and cached behind a [`std::sync::OnceLock`].

use std::sync::OnceLock;

/// Primitive polynomial for GF(256): x^8 + x^4 + x^3 + x^2 + 1.
const PRIM: u16 = 0x11D;
/// Generator element (primitive root) α.
const GENERATOR: u8 = 2;

/// Precomputed exponential and logarithm tables for GF(256).
struct GfTables {
    /// `exp[i] == α^i`. Sized 512 so multiplication can index without a
    /// modular reduction (`exp[(log_a + log_b)]` with the sum up to 510).
    exp: [u8; 512],
    /// `log[v] == i` such that `α^i == v` (undefined / unused for v == 0).
    log: [u8; 256],
}

/// Build the GF(256) exp/log tables using the primitive polynomial.
fn build_tables() -> GfTables {
    let mut exp = [0u8; 512];
    let mut log = [0u8; 256];

    let mut x: u16 = 1;
    for i in 0..255usize {
        exp[i] = x as u8;
        log[x as usize] = i as u8;
        // Multiply x by the generator α = 2 in GF(256).
        x <<= 1;
        if x & 0x100 != 0 {
            x ^= PRIM;
        }
    }
    // Extend the exp table so indices up to 510 are valid (avoids mod 255).
    for i in 255..512usize {
        exp[i] = exp[i - 255];
    }

    GfTables { exp, log }
}

/// Access the cached GF(256) tables, building them on first use.
fn tables() -> &'static GfTables {
    static TABLES: OnceLock<GfTables> = OnceLock::new();
    TABLES.get_or_init(build_tables)
}

// ---------------------------------------------------------------------------
// GF(256) field arithmetic
// ---------------------------------------------------------------------------

/// Multiply two field elements. `gf_mul(0, _) == gf_mul(_, 0) == 0`.
fn gf_mul(a: u8, b: u8) -> u8 {
    if a == 0 || b == 0 {
        return 0;
    }
    let t = tables();
    let la = t.log[a as usize] as usize;
    let lb = t.log[b as usize] as usize;
    t.exp[la + lb]
}

/// Divide `a` by `b` in the field. Panics if `b == 0`.
fn gf_div(a: u8, b: u8) -> u8 {
    assert!(b != 0, "gf256: division by zero");
    if a == 0 {
        return 0;
    }
    let t = tables();
    let la = t.log[a as usize] as usize;
    let lb = t.log[b as usize] as usize;
    // (la - lb) mod 255, kept non-negative by adding 255.
    t.exp[(la + 255 - lb) % 255]
}

/// Raise a field element to an (arbitrary, possibly large) power.
fn gf_pow(a: u8, power: i64) -> u8 {
    if a == 0 {
        // 0^0 is conventionally 1; 0^positive is 0.
        return if power == 0 { 1 } else { 0 };
    }
    let t = tables();
    let la = t.log[a as usize] as i64;
    // Reduce the exponent of the log into [0, 254].
    let mut idx = (la * power) % 255;
    if idx < 0 {
        idx += 255;
    }
    t.exp[idx as usize]
}

/// Multiplicative inverse of a non-zero field element.
fn gf_inverse(a: u8) -> u8 {
    assert!(a != 0, "gf256: inverse of zero");
    let t = tables();
    let la = t.log[a as usize] as usize;
    t.exp[255 - la]
}

// ---------------------------------------------------------------------------
// Polynomial arithmetic over GF(256)
//
// Polynomials are stored most-significant coefficient first:
// `p[0]` is the coefficient of the highest-degree term.
// ---------------------------------------------------------------------------

/// Multiply two polynomials.
fn poly_mul(p: &[u8], q: &[u8]) -> Vec<u8> {
    if p.is_empty() || q.is_empty() {
        return Vec::new();
    }
    let mut r = vec![0u8; p.len() + q.len() - 1];
    for (i, &pi) in p.iter().enumerate() {
        if pi == 0 {
            continue;
        }
        for (j, &qj) in q.iter().enumerate() {
            r[i + j] ^= gf_mul(pi, qj);
        }
    }
    r
}

/// Evaluate a polynomial at `x` using Horner's method.
fn poly_eval(p: &[u8], x: u8) -> u8 {
    let mut y = 0u8;
    for &coef in p {
        y = gf_mul(y, x) ^ coef;
    }
    y
}

/// Multiply every coefficient of `p` by the scalar `x`.
fn poly_scale(p: &[u8], x: u8) -> Vec<u8> {
    p.iter().map(|&c| gf_mul(c, x)).collect()
}

/// Add two polynomials (XOR), aligning on the least-significant term.
fn poly_add(p: &[u8], q: &[u8]) -> Vec<u8> {
    let len = p.len().max(q.len());
    let mut r = vec![0u8; len];
    // Right-align (low-order terms share the same tail index).
    for (i, &c) in p.iter().enumerate() {
        r[i + len - p.len()] ^= c;
    }
    for (i, &c) in q.iter().enumerate() {
        r[i + len - q.len()] ^= c;
    }
    r
}

/// Reed–Solomon generator polynomial: ∏_{i=0}^{nsym-1} (x - α^i).
fn rs_generator_poly(nsym: usize) -> Vec<u8> {
    let mut g = vec![1u8];
    for i in 0..nsym {
        // (x - α^i) == (x + α^i) in GF(2^k): coefficients [1, α^i].
        let factor = [1u8, gf_pow(GENERATOR, i as i64)];
        g = poly_mul(&g, &factor);
    }
    g
}

// ---------------------------------------------------------------------------
// Public codec
// ---------------------------------------------------------------------------

/// A systematic Reed–Solomon codec over GF(256) with `nsym` parity symbols.
#[derive(Debug, Clone)]
pub struct ReedSolomon {
    /// Number of parity (error-correction) symbols appended per codeword.
    pub nsym: usize,
}

impl ReedSolomon {
    /// Create a codec that appends `nsym` parity bytes per codeword.
    ///
    /// `nsym` error-correction symbols can repair up to `nsym / 2` byte errors.
    pub fn new(nsym: usize) -> Self {
        ReedSolomon { nsym }
    }

    /// Systematically encode `data`, returning the original bytes followed by
    /// `nsym` parity bytes (length `data.len() + nsym`).
    ///
    /// Panics if `data.len() + nsym > 255` (a single GF(256) codeword cannot
    /// exceed 255 symbols).
    pub fn encode(&self, data: &[u8]) -> Vec<u8> {
        assert!(
            data.len() + self.nsym <= 255,
            "Reed-Solomon: codeword length {} exceeds GF(256) limit of 255",
            data.len() + self.nsym
        );

        if self.nsym == 0 {
            return data.to_vec();
        }

        let gen = rs_generator_poly(self.nsym);

        // Compute parity = remainder of (data · x^nsym) mod gen via synthetic
        // division. We operate on a buffer of length data.len() + nsym whose
        // trailing nsym positions accumulate the parity.
        let mut out = vec![0u8; data.len() + self.nsym];
        out[..data.len()].copy_from_slice(data);

        // `gen[0]` is 1 by construction, so we can skip dividing by the lead.
        for i in 0..data.len() {
            let coef = out[i];
            if coef != 0 {
                // Skip gen[0] (== 1).
                for j in 1..gen.len() {
                    out[i + j] ^= gf_mul(gen[j], coef);
                }
            }
        }

        // At this point out[..data.len()] still holds the (untouched) message
        // bytes, but the synthetic division clobbered them as it went. Restore
        // the systematic prefix and keep the computed parity tail.
        let parity_start = data.len();
        let mut result = Vec::with_capacity(data.len() + self.nsym);
        result.extend_from_slice(data);
        result.extend_from_slice(&out[parity_start..]);
        result
    }

    /// Decode `received`, correcting up to `nsym / 2` byte errors and returning
    /// the message with the `nsym` parity bytes stripped.
    ///
    /// Returns `Err` if the codeword has more errors than can be corrected.
    pub fn decode(&self, received: &[u8]) -> Result<Vec<u8>, String> {
        if self.nsym == 0 {
            return Ok(received.to_vec());
        }
        if received.len() < self.nsym {
            return Err("Reed-Solomon: received codeword shorter than parity".to_string());
        }

        let msg_len = received.len() - self.nsym;

        // 1. Syndromes. S_i = R(α^i) for i in 0..nsym.
        let synd = self.calc_syndromes(received);
        if synd.iter().all(|&s| s == 0) {
            // No errors detected.
            return Ok(received[..msg_len].to_vec());
        }

        // 2. Berlekamp–Massey → error-locator polynomial Λ(x).
        let err_loc = self.berlekamp_massey(&synd);

        // Number of errors == degree of the locator polynomial.
        let num_errors = err_loc.len() - 1;
        if num_errors == 0 || num_errors > self.nsym / 2 {
            return Err("Reed-Solomon: too many errors to correct".to_string());
        }

        // 3. Chien search → error positions.
        let err_pos = self.find_error_positions(&err_loc, received.len())?;
        if err_pos.len() != num_errors {
            return Err("Reed-Solomon: too many errors to correct".to_string());
        }

        // 4. Forney → magnitudes; apply corrections.
        let corrected = self.correct_errors(received, &synd, &err_loc, &err_pos)?;

        // 5. Verify by recomputing syndromes on the corrected word.
        let verify = self.calc_syndromes(&corrected);
        if verify.iter().any(|&s| s != 0) {
            return Err("Reed-Solomon: too many errors to correct".to_string());
        }

        Ok(corrected[..msg_len].to_vec())
    }

    /// Compute the `nsym` syndromes S_i = R(α^i), most-significant first.
    fn calc_syndromes(&self, received: &[u8]) -> Vec<u8> {
        (0..self.nsym)
            .map(|i| poly_eval(received, gf_pow(GENERATOR, i as i64)))
            .collect()
    }

    /// Berlekamp–Massey: derive the error-locator polynomial from syndromes.
    /// Returns Λ(x) most-significant coefficient first, with Λ(0) leading term
    /// normalized so the trailing (constant) coefficient is 1.
    fn berlekamp_massey(&self, synd: &[u8]) -> Vec<u8> {
        // Work least-significant-first internally for clarity, then reverse.
        // err_loc and old_loc are stored MSB-first as Vec<u8>.
        let mut err_loc: Vec<u8> = vec![1];
        let mut old_loc: Vec<u8> = vec![1];

        for i in 0..synd.len() {
            // Compute discrepancy delta.
            let mut delta = synd[i];
            for j in 1..err_loc.len() {
                delta ^= gf_mul(err_loc[err_loc.len() - 1 - j], synd[i - j]);
            }

            // Shift old_loc by multiplying by x (append a trailing zero).
            old_loc.push(0);

            if delta != 0 {
                if old_loc.len() > err_loc.len() {
                    // new_loc = scale(old_loc, delta); old_loc = scale(err_loc, 1/delta)
                    let mut new_loc = poly_scale(&old_loc, delta);
                    old_loc = poly_scale(&err_loc, gf_inverse(delta));
                    std::mem::swap(&mut err_loc, &mut new_loc);
                }
                // err_loc = err_loc + scale(old_loc, delta)
                err_loc = poly_add(&err_loc, &poly_scale(&old_loc, delta));
            }
        }

        // Strip leading zeros.
        let first_nonzero = err_loc.iter().position(|&c| c != 0).unwrap_or(0);
        err_loc[first_nonzero..].to_vec()
    }

    /// Chien search: evaluate Λ(α^-i) for each codeword index `i`; a root means
    /// position `i` (counting from the right end) holds an error.
    ///
    /// Returns error positions as indices into `received` (left-to-right).
    fn find_error_positions(
        &self,
        err_loc: &[u8],
        codeword_len: usize,
    ) -> Result<Vec<usize>, String> {
        let errs = err_loc.len() - 1;
        let mut positions = Vec::new();

        // For an error at codeword index `pos`, the error-location value is
        // X = α^(n-1-pos) and the locator Λ(x) = ∏(1 - X·x) has a root at
        // x = X^-1 = α^-(n-1-pos). So test Λ(α^-(n-1-pos)) for each index.
        for pos in 0..codeword_len {
            let k = (codeword_len - 1 - pos) as i64; // position counting from right
            let val = poly_eval(err_loc, gf_pow(GENERATOR, -k));
            if val == 0 {
                positions.push(pos);
            }
        }

        if positions.len() != errs {
            return Err("Reed-Solomon: too many errors to correct".to_string());
        }
        Ok(positions)
    }

    /// Forney algorithm: compute error magnitudes and apply them.
    fn correct_errors(
        &self,
        received: &[u8],
        synd: &[u8],
        err_loc: &[u8],
        err_pos: &[usize],
    ) -> Result<Vec<u8>, String> {
        let n = received.len();

        // Syndrome polynomial, MSB-first: coefficients are S_{nsym-1} .. S_0.
        let synd_poly: Vec<u8> = synd.iter().rev().cloned().collect();

        // Error evaluator Ω(x) = (S(x) · Λ(x)) mod x^nsym.
        let mut omega = poly_mul(&synd_poly, err_loc);
        // Keep only the lowest `nsym` coefficients (mod x^nsym): that's the
        // last `nsym` entries of the MSB-first product.
        if omega.len() > self.nsym {
            omega = omega[omega.len() - self.nsym..].to_vec();
        }

        // Formal derivative of Λ(x). For GF(2^k), Λ'(x) keeps only odd-power
        // terms (even-index from the low end), shifted down by one.
        let err_loc_deriv = formal_derivative(err_loc);

        let mut corrected = received.to_vec();

        for &pos in err_pos {
            // X = α^(position-from-right).
            let pos_from_right = (n - 1 - pos) as i64;
            let xi = gf_pow(GENERATOR, pos_from_right);
            let xi_inv = gf_inverse(xi);

            // Numerator = Ω(X^-1); Denominator = Λ'(X^-1).
            let num = poly_eval(&omega, xi_inv);
            let den = poly_eval(&err_loc_deriv, xi_inv);

            if den == 0 {
                return Err("Reed-Solomon: too many errors to correct".to_string());
            }

            // Forney: magnitude = X · Ω(X^-1) / Λ'(X^-1).
            let magnitude = gf_mul(xi, gf_div(num, den));

            corrected[pos] ^= magnitude;
        }

        Ok(corrected)
    }
}

/// Formal derivative of a polynomial (MSB-first) over GF(2^k).
///
/// In characteristic 2, d/dx of `c·x^k` is `c·x^(k-1)` when `k` is odd and `0`
/// when `k` is even. We return the result MSB-first.
fn formal_derivative(p: &[u8]) -> Vec<u8> {
    // Degree of the polynomial.
    if p.len() <= 1 {
        return vec![0];
    }
    let deg = p.len() - 1;
    let mut out = vec![0u8; deg]; // degrees 0..deg-1
    for (i, &c) in p.iter().enumerate() {
        let power = deg - i; // power of x for this coefficient
        if power == 0 {
            continue;
        }
        if power % 2 == 1 {
            // Coefficient of resulting degree (power - 1), MSB-first index.
            // out has length `deg`; resulting degree power-1 maps to index
            // (deg - 1) - (power - 1) = deg - power.
            out[deg - power] = c;
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Tiny deterministic LCG for reproducible "random" positions/values.
    struct Lcg(u64);
    impl Lcg {
        fn new(seed: u64) -> Self {
            Lcg(seed)
        }
        fn next_u32(&mut self) -> u32 {
            // Numerical Recipes LCG constants.
            self.0 = self
                .0
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            (self.0 >> 33) as u32
        }
        fn below(&mut self, n: usize) -> usize {
            (self.next_u32() as usize) % n
        }
    }

    // ----- Field arithmetic sanity -----

    #[test]
    fn gf_basic_properties() {
        assert_eq!(gf_mul(0, 5), 0);
        assert_eq!(gf_mul(5, 0), 0);
        assert_eq!(gf_mul(1, 123), 123);
        // a * a^-1 == 1 for all non-zero a.
        for a in 1u8..=255 {
            assert_eq!(gf_mul(a, gf_inverse(a)), 1, "inverse failed for {}", a);
        }
        // div is inverse of mul.
        for a in 1u8..=50 {
            for b in 1u8..=50 {
                let p = gf_mul(a, b);
                assert_eq!(gf_div(p, b), a);
            }
        }
        // pow consistency.
        assert_eq!(gf_pow(2, 0), 1);
        assert_eq!(gf_pow(2, 1), 2);
        assert_eq!(gf_mul(gf_pow(3, 5), gf_pow(3, -5)), 1);
    }

    #[test]
    fn poly_helpers() {
        // (x + 1)(x + 1) = x^2 + 1 over GF(2^k) since 1 XOR 1 = 0.
        let p = poly_mul(&[1, 1], &[1, 1]);
        assert_eq!(p, vec![1, 0, 1]);
        // Horner eval of x^2 + 1 at x = 2 -> 4 ^ 1 = 5.
        assert_eq!(poly_eval(&[1, 0, 1], 2), 5);
        // scale.
        assert_eq!(poly_scale(&[1, 2, 3], 2), vec![2, 4, 6]);
        // add (XOR) right-aligned.
        assert_eq!(poly_add(&[1, 2, 3], &[1, 1]), vec![1, 3, 2]);
    }

    #[test]
    fn generator_poly_shape() {
        // Generator of nsym symbols has degree nsym (length nsym + 1) and a
        // leading coefficient of 1.
        for nsym in [2usize, 4, 8, 10] {
            let g = rs_generator_poly(nsym);
            assert_eq!(g.len(), nsym + 1);
            assert_eq!(g[0], 1);
        }
    }

    // ----- Round trips -----

    #[test]
    fn clean_round_trip() {
        let messages: Vec<Vec<u8>> = vec![
            b"hello world".to_vec(),
            b"".to_vec(),
            vec![0u8; 20],
            (0u8..40).collect(),
            b"Reed-Solomon GF(256) systematic codec".to_vec(),
        ];
        for nsym in [8usize, 10] {
            let rs = ReedSolomon::new(nsym);
            for msg in &messages {
                let enc = rs.encode(msg);
                assert_eq!(enc.len(), msg.len() + nsym);
                // Systematic: message bytes appear unchanged at the front.
                assert_eq!(&enc[..msg.len()], &msg[..]);
                let dec = rs.decode(&enc).expect("clean decode must succeed");
                assert_eq!(&dec, msg, "round trip mismatch nsym={}", nsym);
            }
        }
    }

    #[test]
    fn single_error_pipeline() {
        // Exercise each decode stage explicitly for a single-byte error.
        let rs = ReedSolomon::new(8);
        let msg = b"hello world".to_vec();
        let mut enc = rs.encode(&msg);
        let orig = enc.clone();
        enc[2] ^= 0xAB;

        let synd = rs.calc_syndromes(&enc);
        assert!(synd.iter().any(|&s| s != 0));
        let loc = rs.berlekamp_massey(&synd);
        let pos = rs.find_error_positions(&loc, enc.len()).unwrap();
        assert_eq!(pos, vec![2]);
        let corr = rs.correct_errors(&enc, &synd, &loc, &pos).unwrap();
        assert_eq!(corr, orig);
    }

    #[test]
    fn known_small_vector() {
        // Encode then corrupt a couple bytes and recover.
        let rs = ReedSolomon::new(10);
        let msg = b"hello world".to_vec();
        let mut enc = rs.encode(&msg);
        // Corrupt up to 5 (= 10/2) bytes.
        enc[0] ^= 0xFF;
        enc[3] ^= 0x0F;
        enc[7] ^= 0x77;
        let dec = rs.decode(&enc).expect("should correct 3 errors");
        assert_eq!(dec, msg);
    }

    // ----- Correctable error injection: floor(nsym/2) errors -----

    #[test]
    fn corrects_max_errors() {
        let mut rng = Lcg::new(0xDEAD_BEEF);
        for nsym in [8usize, 10] {
            let rs = ReedSolomon::new(nsym);
            let max_err = nsym / 2;
            for trial in 0..50 {
                // Random message length 1..=40.
                let len = 1 + rng.below(40);
                let msg: Vec<u8> = (0..len).map(|_| rng.next_u32() as u8).collect();
                let mut enc = rs.encode(&msg);

                // Pick `max_err` distinct positions.
                let mut positions = Vec::new();
                while positions.len() < max_err {
                    let p = rng.below(enc.len());
                    if !positions.contains(&p) {
                        positions.push(p);
                    }
                }
                // Inject non-zero errors.
                for &p in &positions {
                    let mut e = (rng.next_u32() as u8) | 1; // ensure non-zero
                    if e == 0 {
                        e = 1;
                    }
                    enc[p] ^= e;
                }

                let dec = rs
                    .decode(&enc)
                    .unwrap_or_else(|e| panic!("nsym={} trial={} failed: {}", nsym, trial, e));
                assert_eq!(dec, msg, "nsym={} trial={} recovery mismatch", nsym, trial);
            }
        }
    }

    // ----- Too many errors should fail -----

    #[test]
    fn too_many_errors_rejected() {
        let mut rng = Lcg::new(0x1234_5678);
        for nsym in [8usize, 10] {
            let rs = ReedSolomon::new(nsym);
            let too_many = nsym / 2 + 2; // strictly beyond correction capacity
            let mut err_count = 0;
            let mut ok_but_correct = 0;
            let trials = 60;
            for _ in 0..trials {
                let len = 10 + rng.below(30);
                let msg: Vec<u8> = (0..len).map(|_| rng.next_u32() as u8).collect();
                let mut enc = rs.encode(&msg);

                let inject = too_many.min(enc.len());
                let mut positions = Vec::new();
                while positions.len() < inject {
                    let p = rng.below(enc.len());
                    if !positions.contains(&p) {
                        positions.push(p);
                    }
                }
                for &p in &positions {
                    let e = (rng.next_u32() as u8) | 1;
                    enc[p] ^= e;
                }

                match rs.decode(&enc) {
                    Err(_) => err_count += 1,
                    Ok(d) => {
                        // Acceptable only if it genuinely recovers the original.
                        if d == msg {
                            ok_but_correct += 1;
                        } else {
                            panic!(
                                "nsym={} decode returned wrong message for over-capacity errors",
                                nsym
                            );
                        }
                    }
                }
            }
            // The overwhelming majority must be rejected as uncorrectable.
            assert!(
                err_count + ok_but_correct == trials,
                "every over-capacity case must be Err or exactly-correct"
            );
            assert!(
                err_count > 0,
                "nsym={} expected at least some uncorrectable rejections",
                nsym
            );
        }
    }

    #[test]
    fn no_errors_after_encode() {
        let rs = ReedSolomon::new(8);
        let msg = b"syndromes should be zero".to_vec();
        let enc = rs.encode(&msg);
        let synd = rs.calc_syndromes(&enc);
        assert!(
            synd.iter().all(|&s| s == 0),
            "valid codeword has zero syndromes"
        );
    }
}
